class article{
    constructor(id, author, date, subject, content){
        this.id = id;
        this.author = author;
        this.date = date;
        this.subject = subject;
        this.content = content;
    }
}

const data = [   
    new article( 0, " Elon Musk","01/04/2021","random subject","Nam volutpat mollis ante venenatis dapibus. Phasellus vitae mi sodales, feugiat lectus eget, posuere odio. Mauris laoreet nisl id eros varius bibendum. Sed semper sapien orci, eget convallis leo rutrum quis. Nulla et ipsum vitae magna vulputate efficitur. Etiam sit amet purus diam. Proin et sem nisl. Phasellus ac metus at massa viverra convallis sit amet vitae dolor. Fusce ultricies accumsan lectus, nec viverra risus. Phasellus sed pellentesque ligula. Proin egestas posuere dolor, at efficitur diam molestie eget. Quisque eros justo, fermentum non rhoncus non, lobortis eget turpis. Fusce bibendum ex lacus. Vivamus in vulputate odio. In efficitur consequat massa, vel tempus odio consectetur sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."),
    new article( 1, " Jeff Bezos","03/04/2021","random subject","Suspendisse sagittis augue id gravida lacinia. Quisque eros risus, lobortis sed sapien id, sagittis iaculis lacus. Curabitur consectetur vulputate rutrum. Sed accumsan ipsum et nisl hendrerit sagittis. Donec efficitur vitae lectus id molestie. Sed eu fermentum odio. Vestibulum ultrices odio lorem, vitae lobortis est vehicula sit amet. Aenean faucibus ut lacus accumsan molestie. Vivamus efficitur nisl ac maximus auctor. Morbi at consectetur tortor. Nam hendrerit lorem nulla, ut rhoncus urna faucibus sit amet. Nunc rhoncus vulputate finibus. Duis id tempor risus. Interdum et malesuada fames ac ante ipsum primis in faucibus."), 
    new article( 2, " Mark Zuckerberg","04/04/2021","random subject","Nulla gravida fringilla ligula. Curabitur commodo feugiat elit tempus dapibus. Sed at ipsum vulputate massa sagittis iaculis. Nulla facilisi. Proin venenatis sapien nisl, quis feugiat risus tristique vel. Fusce sodales feugiat mi, et rhoncus odio sagittis quis. Quisque rutrum massa felis, et dapibus quam dapibus vel. Quisque vel nulla pulvinar, tempus risus vitae, fringilla felis. Pellentesque vitae nulla porttitor, consequat orci ut, tempus turpis. Maecenas quis aliquam est, vitae dignissim enim. Ut sit amet fermentum libero. Vestibulum scelerisque lorem augue, sit amet ullamcorper turpis pharetra eget. Sed lacinia massa in mi lacinia, sed blandit massa ultricies. Ut eget aliquam sem. Aenean dapibus nisl felis, ut pellentesque nunc rutrum ac. Ut congue dolor nec elementum vulputate."),
    new article( 3, " Tim Cook","05/04/2021","random subject","Sed vitae libero quam. Donec nec mauris in est dapibus aliquam ac eu arcu. Quisque aliquet sem nisl, et molestie justo laoreet vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam aliquet urna eu nunc condimentum ultrices non vel augue. In porta posuere ligula, ac imperdiet ante porttitor vitae. Ut semper dapibus dui at rutrum. Integer ut magna in neque hendrerit tincidunt. Donec gravida dui eu arcu facilisis, vitae porttitor massa efficitur. Praesent sagittis, orci condimentum lobortis sagittis, metus orci ullamcorper tortor, feugiat vestibulum ex metus ac urna. Mauris tempus elit lacus, in dignissim lacus faucibus id. Nam rhoncus molestie odio, a luctus odio varius eget. Phasellus ornare aliquet lectus, nec dapibus ligula finibus vitae. Phasellus accumsan consectetur pharetra. Integer a ante urna.    "),
    new article( 4, " Ryan Dahl","06/04/2021","random subject","Nam volutpat mollis ante venenatis dapibus. Phasellus vitae mi sodales, feugiat lectus eget, posuere odio. Mauris laoreet nisl id eros varius bibendum. Sed semper sapien orci, eget convallis leo rutrum quis. Nulla et ipsum vitae magna vulputate efficitur. Etiam sit amet purus diam. Proin et sem nisl. Phasellus ac metus at massa viverra convallis sit amet vitae dolor. Fusce ultricies accumsan lectus, nec viverra risus. Phasellus sed pellentesque ligula. Proin egestas posuere dolor, at efficitur diam molestie eget. Quisque eros justo, fermentum non rhoncus non, lobortis eget turpis. Fusce bibendum ex lacus. Vivamus in vulputate odio. In efficitur consequat massa, vel tempus odio consectetur sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."),
    new article( 5, " Linus Torvalds","07/04/2021","random subject","Suspendisse sagittis augue id gravida lacinia. Quisque eros risus, lobortis sed sapien id, sagittis iaculis lacus. Curabitur consectetur vulputate rutrum. Sed accumsan ipsum et nisl hendrerit sagittis. Donec efficitur vitae lectus id molestie. Sed eu fermentum odio. Vestibulum ultrices odio lorem, vitae lobortis est vehicula sit amet. Aenean faucibus ut lacus accumsan molestie. Vivamus efficitur nisl ac maximus auctor. Morbi at consectetur tortor. Nam hendrerit lorem nulla, ut rhoncus urna faucibus sit amet. Nunc rhoncus vulputate finibus. Duis id tempor risus. Interdum et malesuada fames ac ante ipsum primis in faucibus."),
    new article( 6, " Steve Jobs","08/04/2021","random subject","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
    new article( 7, " Larry Page","09/04/2021","random subject","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
    new article( 8, " Jack Dorsey","10/04/2021","random subject","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
    new article( 9, " Guido Van Rossum","10/04/2021","random subject","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
];

exports.getArticleById = function(id){
return data[id];
}
exports.allArticle = data;
