class course{
    constructor(id, name, coursecontent, price){
        this.id = id;
        this.name = name;
        this.coursecontent = coursecontent;
        this.price = price;
    }
}

const data = [   
    new course( 0, "Mongo","Cras in condimentum metus, vel porttitor libero. Fusce venenatis ullamcorper vehicula. Integer hendrerit, dolor in elementum facilisis, leo lectus ornare diam, sit amet posuere quam nisl id dui. Pellentesque congue quam vel tortor blandit tristique. Donec viverra tincidunt mi, id lobortis dolor lacinia blandit. Praesent tincidunt ligula risus, id ornare mauris dictum quis. Curabitur erat metus, malesuada non rutrum vel, euismod sed dui. Pellentesque ac vestibulum odio, at bibendum est. Suspendisse potenti. Aliquam convallis dui quis malesuada blandit. Vivamus id accumsan risus, sit amet suscipit odio.","1 BTC"),
    new course( 1, "Mongoo","Nunc ac nisi iaculis, cursus eros vitae, feugiat ipsum. Nulla auctor urna quis metus malesuada, sed interdum risus pellentesque. Praesent lacinia justo non metus ultricies, et porttitor tellus accumsan. Nulla facilisi. Proin suscipit pellentesque mi eget convallis. In hendrerit ligula id arcu convallis, quis volutpat mauris condimentum. Nulla congue lacinia turpis eget consequat. Phasellus eu scelerisque velit. Vivamus libero nisl, interdum id tristique sed, fermentum vitae mi. Nullam nec lorem eu neque ornare aliquet. Curabitur quis dignissim orci.","random content","1 BTC"), 
    new course( 2, "Mongooo","Proin purus massa, mattis at tempus nec, porta vitae purus. Sed vulputate volutpat velit, eu ornare ligula aliquam eu. In lorem mi, egestas a aliquam sit amet, tempus sit amet dui. Mauris elementum metus vel leo cursus, ut bibendum velit suscipit. Praesent lobortis odio sit amet elit molestie euismod. Vivamus tristique semper massa in mollis. Pellentesque felis leo, egestas sit amet arcu nec, imperdiet commodo tellus. Fusce consectetur hendrerit pretium. Morbi diam orci, lobortis sit amet porttitor id, vestibulum eu arcu. Cras sed ex ac sapien egestas accumsan. Ut sed ornare sapien. Phasellus semper dignissim ligula vitae viverra.","1 BTC"),
    new course( 3, "Mongoooo","Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tincidunt mollis mi eget suscipit. Cras lobortis arcu vel odio consequat, quis finibus tellus fermentum. Ut sollicitudin mauris sit amet faucibus sagittis. Nulla rhoncus nunc non est consequat, gravida scelerisque libero dignissim. Integer elementum ligula ac volutpat congue. Aenean dignissim quam et elit fringilla, quis pharetra metus faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla id purus ut odio sagittis pharetra at cursus mi. Cras interdum leo eu pretium tempus. Vestibulum accumsan dui quis auctor pharetra. Cras eget lectus quis diam porta faucibus.","1 BTC"),
    new course( 4, "Mongooooo","Pellentesque aliquam aliquet tincidunt. Etiam malesuada non sem sed gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam et quam nec mi venenatis porta non vitae lorem. Nunc commodo scelerisque aliquet. Morbi a metus et augue varius finibus quis in nunc. Pellentesque luctus vestibulum sapien id ultricies. Phasellus quam eros, suscipit quis tincidunt quis, aliquam a quam. Duis vitae ullamcorper sem. Etiam accumsan nunc at leo facilisis, non scelerisque augue sollicitudin.","random content","1 BTC"),
    new course( 5, "Node","Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tincidunt mollis mi eget suscipit. Cras lobortis arcu vel odio consequat, quis finibus tellus fermentum. Ut sollicitudin mauris sit amet faucibus sagittis. Nulla rhoncus nunc non est consequat, gravida scelerisque libero dignissim. Integer elementum ligula ac volutpat congue. Aenean dignissim quam et elit fringilla, quis pharetra metus faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla id purus ut odio sagittis pharetra at cursus mi. Cras interdum leo eu pretium tempus. Vestibulum accumsan dui quis auctor pharetra. Cras eget lectus quis diam porta faucibus.","1 BTC"),
    new course( 6, "Noode","Proin purus massa, mattis at tempus nec, porta vitae purus. Sed vulputate volutpat velit, eu ornare ligula aliquam eu. In lorem mi, egestas a aliquam sit amet, tempus sit amet dui. Mauris elementum metus vel leo cursus, ut bibendum velit suscipit. Praesent lobortis odio sit amet elit molestie euismod. Vivamus tristique semper massa in mollis. Pellentesque felis leo, egestas sit amet arcu nec, imperdiet commodo tellus. Fusce consectetur hendrerit pretium. Morbi diam orci, lobortis sit amet porttitor id, vestibulum eu arcu. Cras sed ex ac sapien egestas accumsan. Ut sed ornare sapien. Phasellus semper dignissim ligula vitae viverra.","1 BTC"),
    new course( 7, "Nooode","Nunc ac nisi iaculis, cursus eros vitae, feugiat ipsum. Nulla auctor urna quis metus malesuada, sed interdum risus pellentesque. Praesent lacinia justo non metus ultricies, et porttitor tellus accumsan. Nulla facilisi. Proin suscipit pellentesque mi eget convallis. In hendrerit ligula id arcu convallis, quis volutpat mauris condimentum. Nulla congue lacinia turpis eget consequat. Phasellus eu scelerisque velit. Vivamus libero nisl, interdum id tristique sed, fermentum vitae mi. Nullam nec lorem eu neque ornare aliquet. Curabitur quis dignissim orci.","1 BTC"),
    new course( 8, "Noooode","Cras in condimentum metus, vel porttitor libero. Fusce venenatis ullamcorper vehicula. Integer hendrerit, dolor in elementum facilisis, leo lectus ornare diam, sit amet posuere quam nisl id dui. Pellentesque congue quam vel tortor blandit tristique. Donec viverra tincidunt mi, id lobortis dolor lacinia blandit. Praesent tincidunt ligula risus, id ornare mauris dictum quis. Curabitur erat metus, malesuada non rutrum vel, euismod sed dui. Pellentesque ac vestibulum odio, at bibendum est. Suspendisse potenti. Aliquam convallis dui quis malesuada blandit. Vivamus id accumsan risus, sit amet suscipit odio.","1 BTC"),
    new course( 9, "Nooooode","Nunc ac nisi iaculis, cursus eros vitae, feugiat ipsum. Nulla auctor urna quis metus malesuada, sed interdum risus pellentesque. Praesent lacinia justo non metus ultricies, et porttitor tellus accumsan. Nulla facilisi. Proin suscipit pellentesque mi eget convallis. In hendrerit ligula id arcu convallis, quis volutpat mauris condimentum. Nulla congue lacinia turpis eget consequat. Phasellus eu scelerisque velit. Vivamus libero nisl, interdum id tristique sed, fermentum vitae mi. Nullam nec lorem eu neque ornare aliquet. Curabitur quis dignissim orci.","1 BTC"),
];

exports.getCourseById = function(id){
return data[id];
}
exports.allCourse = data;